version: '3.7'

services:

 # postgres:
  #  image: postgres:16.2-alpine3.19
   # container_name: evecheckDB
   # ports:
    #  - 5432:5432
   # environment:
    #  - POSTGRES_USER=admin
     # - POSTGRES_PASSWORD=admin
     # - POSTGRES_DB=evecheck
   # volumes:
    #  - 'db:/var/lib/postgresql/data'
   # networks:
    #  - evecheck

  projectapi:
    build:
      context: .
    container_name: projectapi
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_BASE_URL=http://localhost:3333
  #  depends_on:
   #   - postgres
    networks:
      - projecta
networks:
  projecta:
    driver: bridge
volumes:
  db: