/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/room.glb --types -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Nightstand: THREE.Mesh
    Lamp: THREE.Mesh
    Vase_1: THREE.Mesh
    Vase_2: THREE.Mesh
    Painting: THREE.Mesh
    Plane002: THREE.Mesh
    underneath1: THREE.Mesh
    switch2: THREE.Mesh
    switch1: THREE.Mesh
    switch_plastic: THREE.Mesh
    StringhE: THREE.Mesh
    StringG: THREE.Mesh
    Stringend: THREE.Mesh
    Stringe: THREE.Mesh
    StringD: THREE.Mesh
    StringB: THREE.Mesh
    StringA: THREE.Mesh
    screwy: THREE.Mesh
    screwx: THREE.Mesh
    screw5: THREE.Mesh
    screw2: THREE.Mesh
    screw: THREE.Mesh
    plate: THREE.Mesh
    Plane003: THREE.Mesh
    NurbsPath005_1: THREE.Mesh
    NurbsPath005_2: THREE.Mesh
    pickup4: THREE.Mesh
    pickup3: THREE.Mesh
    pickup2: THREE.Mesh
    pickup1: THREE.Mesh
    NurbsPath_1: THREE.Mesh
    NurbsPath_2: THREE.Mesh
    magnetos3: THREE.Mesh
    magnetos2: THREE.Mesh
    magnetos1: THREE.Mesh
    magnetos0: THREE.Mesh
    knobs001: THREE.Mesh
    knobs: THREE.Mesh
    knob005: THREE.Mesh
    knob004: THREE.Mesh
    knob003: THREE.Mesh
    knob002: THREE.Mesh
    knob001: THREE.Mesh
    knob: THREE.Mesh
    handle2: THREE.Mesh
    handle: THREE.Mesh
    NurbsPath002_1: THREE.Mesh
    NurbsPath002_2: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane010_2: THREE.Mesh
    draaidingcenter1005: THREE.Mesh
    draaidingcenter1004: THREE.Mesh
    draaidingcenter1003: THREE.Mesh
    draaidingcenter1002: THREE.Mesh
    draaidingcenter1001: THREE.Mesh
    draaidingcenter1: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cube022: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Circle059: THREE.Mesh
    Circle058: THREE.Mesh
    Circle057: THREE.Mesh
    Circle056: THREE.Mesh
    Circle055: THREE.Mesh
    Circle054: THREE.Mesh
    Circle053: THREE.Mesh
    Circle052: THREE.Mesh
    Circle051: THREE.Mesh
    Circle050: THREE.Mesh
    Circle049: THREE.Mesh
    Circle048: THREE.Mesh
    Circle047: THREE.Mesh
    Circle046: THREE.Mesh
    Circle045: THREE.Mesh
    Circle044: THREE.Mesh
    Circle043: THREE.Mesh
    Circle042: THREE.Mesh
    Circle041: THREE.Mesh
    Circle040: THREE.Mesh
    Circle039: THREE.Mesh
    Circle038: THREE.Mesh
    Circle037: THREE.Mesh
    Circle036: THREE.Mesh
    Circle035: THREE.Mesh
    Circle034: THREE.Mesh
    Circle033: THREE.Mesh
    Circle032: THREE.Mesh
    Circle031: THREE.Mesh
    Circle030: THREE.Mesh
    Circle029: THREE.Mesh
    Circle028: THREE.Mesh
    Circle027: THREE.Mesh
    Circle026: THREE.Mesh
    Circle025: THREE.Mesh
    Circle024: THREE.Mesh
    Circle023: THREE.Mesh
    Circle022: THREE.Mesh
    Circle021: THREE.Mesh
    Circle020: THREE.Mesh
    Circle019: THREE.Mesh
    Circle018: THREE.Mesh
    Circle017: THREE.Mesh
    Circle016: THREE.Mesh
    Circle015: THREE.Mesh
    Circle014: THREE.Mesh
    Circle013: THREE.Mesh
    Circle012: THREE.Mesh
    Circle011: THREE.Mesh
    Circle010: THREE.Mesh
    Circle009: THREE.Mesh
    Circle008: THREE.Mesh
    Circle007: THREE.Mesh
    Circle006: THREE.Mesh
    Circle005: THREE.Mesh
    Circle004: THREE.Mesh
    Circle003: THREE.Mesh
    Circle002: THREE.Mesh
    Circle060: THREE.Mesh
    Circle: THREE.Mesh
    Sphere016: THREE.Mesh
    Roundcube003_1: THREE.Mesh
    Roundcube003_2: THREE.Mesh
    Roundcube003_3: THREE.Mesh
    Roundcube003_4: THREE.Mesh
    Roundcube003_5: THREE.Mesh
    Roundcube003_6: THREE.Mesh
    Roundcube003_7: THREE.Mesh
    Roundcube003_8: THREE.Mesh
    Roundcube003_9: THREE.Mesh
    Roundcube003_10: THREE.Mesh
    Roundcube001_1: THREE.Mesh
    Roundcube001_2: THREE.Mesh
    Roundcube001_3: THREE.Mesh
    Roundcube001_4: THREE.Mesh
    Roundcube001_5: THREE.Mesh
    Cylinder001: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere002: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder014_2: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
    Cylinder015_3: THREE.Mesh
    Plane029: THREE.Mesh
    Plane029_1: THREE.Mesh
    Plane029_2: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
    Cylinder016_3: THREE.Mesh
    Cylinder016_4: THREE.Mesh
    Cylinder016_5: THREE.Mesh
    Base: THREE.Mesh
    Cube003: THREE.Mesh
    Base001: THREE.Mesh
    Head: THREE.Mesh
    Pillow_left: THREE.Mesh
    Pillow_right: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cylinder: THREE.Mesh
    Icosphere: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube023: THREE.Mesh
    Cadeira_escritorio: THREE.Mesh
    Circle001: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder007: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Sphere006: THREE.Mesh
    Sphere007: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere009: THREE.Mesh
    Sphere010: THREE.Mesh
    Cube001: THREE.Mesh
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
  }
  materials: {
    Nightstand: THREE.MeshStandardMaterial
    Lamp: THREE.MeshStandardMaterial
    Vase: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshPhysicalMaterial
    paint1: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Black plastic']: THREE.MeshStandardMaterial
    METALIC: THREE.MeshStandardMaterial
    ['white plastic']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['METALIC.014']: THREE.MeshStandardMaterial
    ['METALIC.013']: THREE.MeshStandardMaterial
    ['METALIC.012']: THREE.MeshStandardMaterial
    ['METALIC.011']: THREE.MeshStandardMaterial
    ['METALIC.010']: THREE.MeshStandardMaterial
    ['METALIC.009']: THREE.MeshStandardMaterial
    ['METALIC.007']: THREE.MeshStandardMaterial
    ['METALIC.006']: THREE.MeshStandardMaterial
    ['METALIC.005']: THREE.MeshStandardMaterial
    ['METALIC.004']: THREE.MeshStandardMaterial
    ['METALIC.003']: THREE.MeshStandardMaterial
    ['METALIC.002']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['METALIC.001']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Marshall pic']: THREE.MeshStandardMaterial
    ['Black leather']: THREE.MeshStandardMaterial
    ['Corner metal']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
    ['Back ']: THREE.MeshStandardMaterial
    ['Black metall']: THREE.MeshStandardMaterial
    LIght: THREE.MeshStandardMaterial
    ['Black metal']: THREE.MeshStandardMaterial
    ['Black metall.001']: THREE.MeshStandardMaterial
    Pot_02: THREE.MeshStandardMaterial
    Soil: THREE.MeshStandardMaterial
    SnakePlant_Leave: THREE.MeshStandardMaterial
    Pot_03: THREE.MeshStandardMaterial
    Palm_Leaves: THREE.MeshStandardMaterial
    Stalk: THREE.MeshStandardMaterial
    Pot_01: THREE.MeshStandardMaterial
    Coconut: THREE.MeshStandardMaterial
    Epipremium_01: THREE.MeshStandardMaterial
    Epipremium_02: THREE.MeshStandardMaterial
    Metalic: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName =
  | 'CameraAction'
  | 'PaintingAction'
  | 'Plane.002Action'
  | 'underneath1Action'
  | 'switch2Action'
  | 'switch1Action'
  | 'switch plasticAction'
  | 'StringhEAction'
  | 'StringGAction'
  | 'StringendAction'
  | 'StringeAction'
  | 'StringDAction'
  | 'StringBAction'
  | 'StringAAction'
  | 'screwyAction'
  | 'screwxAction'
  | 'screw5Action'
  | 'screw2Action'
  | 'screwAction'
  | 'plateAction'
  | 'Plane.003Action'
  | 'plaatGrootAction'
  | 'pickup4Action'
  | 'pickup3Action'
  | 'pickup2Action'
  | 'pickup1Action'
  | 'mainframeAction'
  | 'magnetos3Action'
  | 'magnetos2Action'
  | 'magnetos1Action'
  | 'magnetos0Action'
  | 'knobs.001Action'
  | 'knobsAction'
  | 'knob.005Action'
  | 'knob.004Action'
  | 'knob.003Action'
  | 'knob.002Action'
  | 'knob.001Action'
  | 'knobAction'
  | 'handle2Action'
  | 'handleAction'
  | 'hals2Action'
  | 'halsAction'
  | 'draaidingcenter1.005Action'
  | 'draaidingcenter1.004Action'
  | 'draaidingcenter1.003Action'
  | 'draaidingcenter1.002Action'
  | 'draaidingcenter1.001Action'
  | 'draaidingcenter1Action'
  | 'Cylinder.008Action'
  | 'Cube.022Action'
  | 'Cube.043Action'
  | 'Cube.044Action'
  | 'Cube.045Action'
  | 'Cube.046Action'
  | 'Cube.047Action'
  | 'Cube.048Action'
  | 'Circle.059Action'
  | 'Circle.058Action'
  | 'Circle.057Action'
  | 'Circle.056Action'
  | 'Circle.055Action'
  | 'Circle.054Action'
  | 'Circle.053Action'
  | 'Circle.052Action'
  | 'Circle.051Action'
  | 'Circle.050Action'
  | 'Circle.049Action'
  | 'Circle.048Action'
  | 'Circle.047Action'
  | 'Circle.046Action'
  | 'Circle.045Action'
  | 'Circle.044Action'
  | 'Circle.043Action'
  | 'Circle.042Action'
  | 'Circle.041Action'
  | 'Circle.040Action'
  | 'Circle.039Action'
  | 'Circle.038Action'
  | 'Circle.037Action'
  | 'Circle.036Action'
  | 'Circle.035Action'
  | 'Circle.034Action'
  | 'Circle.033Action'
  | 'Circle.032Action'
  | 'Circle.031Action'
  | 'Circle.030Action'
  | 'Circle.029Action'
  | 'Circle.028Action'
  | 'Circle.027Action'
  | 'Circle.026Action'
  | 'Circle.025Action'
  | 'Circle.024Action'
  | 'Circle.023Action'
  | 'Circle.022Action'
  | 'Circle.021Action'
  | 'Circle.020Action'
  | 'Circle.019Action'
  | 'Circle.018Action'
  | 'Circle.017Action'
  | 'Circle.016Action'
  | 'Circle.015Action'
  | 'Circle.014Action'
  | 'Circle.013Action'
  | 'Circle.012Action'
  | 'Circle.011Action'
  | 'Circle.010Action'
  | 'Circle.009Action'
  | 'Circle.008Action'
  | 'Circle.007Action'
  | 'Circle.006Action'
  | 'Circle.005Action'
  | 'Circle.004Action'
  | 'Circle.003Action'
  | 'Circle.002Action'
  | 'Circle.060Action'
  | 'CircleAction'
  | 'Sphere.016Action'
  | 'Roundcube.003Action'
  | 'Roundcube.001Action'
  | 'Cylinder.001Action'
  | 'Sphere.001Action'
  | 'SphereAction'
  | 'Sphere.002Action'
  | 'SpotAction'
  | 'SnakePlant_01Action'
  | 'Palm_03Action'
  | 'SnakePlant_02Action'
  | 'Epipremium.001Action'
  | 'BaseAction'
  | 'Cube.003Action'
  | 'Base.001Action'
  | 'HeadAction'
  | 'Pillow_leftAction'
  | 'Pillow_rightAction'
  | 'Cube.004Action'
  | 'Cube.005Action'
  | 'Cube.006Action'
  | 'Cube.007Action'
  | 'Cube.008Action'
  | 'Cube.009Action'
  | 'Cube.010Action'
  | 'Cube.011Action'
  | 'Cube.012Action'
  | 'Cube.013Action'
  | 'Cube.014Action'
  | 'Cube.015Action'
  | 'Cube.016Action'
  | 'Cube.017Action'
  | 'Cube.018Action'
  | 'Cube.019Action'
  | 'Cube.020Action'
  | 'Cube.021Action'
  | 'Cube.033Action'
  | 'Cube.034Action'
  | 'Cube.035Action'
  | 'Cube.036Action'
  | 'Cube.037Action'
  | 'Cube.038Action'
  | 'Cube.039Action'
  | 'Cube.040Action'
  | 'Cube.041Action'
  | 'Cube.042Action'
  | 'CylinderAction'
  | 'IcosphereAction'
  | 'Cylinder.009Action'
  | 'Nightstand Action'
  | 'NightstandAction'
  | 'Nightstand .001Action'
  | 'LampAction'
  | 'Nightstand .002Action'
  | 'VaseAction'
  | 'LightAction'
  | 'Cube.031Action'
  | 'Cube.032Action'
  | 'Cube.023Action'
  | 'Cadeira escritorioAction'
  | 'Circle.001Action'
  | 'Cube.024Action'
  | 'Cube.025Action'
  | 'Cube.026Action'
  | 'Cube.027Action'
  | 'Cube.028Action'
  | 'Cube.029Action'
  | 'Cube.030Action'
  | 'Cylinder.002Action'
  | 'Cylinder.003Action'
  | 'Cylinder.004Action'
  | 'Cylinder.005Action'
  | 'Cylinder.006Action'
  | 'Cylinder.007Action'
  | 'Sphere.003Action'
  | 'Sphere.004Action'
  | 'Sphere.005Action'
  | 'Sphere.006Action'
  | 'Sphere.007Action'
  | 'Sphere.008Action'
  | 'Sphere.009Action'
  | 'Sphere.010Action'
  | 'Cube.001Action'
  | 'CubeAction'
  | 'Cube.002Action'
  | 'PlaneAction'
  | 'Plane.001Action'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const groupRef = useRef<THREE.Group<THREE.Object3DEventMap>>(null);
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/room.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={groupRef}>
      <group name="Scene">
        <group name="Nightstand_" position={[3.626, 0.114, 0.858]} rotation={[0, -1.552, 0]} scale={2.161}>
          <mesh name="Nightstand" geometry={nodes.Nightstand.geometry} material={materials.Nightstand} position={[0, 0.498, 0]} />
        </group>
        <group name="Nightstand_001" position={[3.976, 0.292, 0.801]} scale={1.855}>
          <mesh name="Lamp" geometry={nodes.Lamp.geometry} material={materials.Lamp} position={[0, 0.498, 0]} />
        </group>
        <group name="Nightstand_002" position={[3.429, 0.615, 1.115]} scale={1.312}>
          <group name="Vase" position={[0.075, 0.498, 0]}>
            <mesh name="Vase_1" geometry={nodes.Vase_1.geometry} material={materials.Vase} />
            <mesh name="Vase_2" geometry={nodes.Vase_2.geometry} material={materials['Material.009']} />
          </group>
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={68.039} position={[-5.099, 3.294, 2.124]} rotation={[-0.922, -0.655, -0.699]} />
        <spotLight name="Spot" intensity={60107.222} angle={1.077} penumbra={0.15} decay={2} color="#ff7ddf" position={[-2.36, 5.925, -1.891]} rotation={[-1.538, -0.225, -0.036]}>
          <group position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Light" intensity={9049.512} decay={2} color="#fff399" position={[3.725, 2.244, 0.669]} rotation={[-1.839, 0.602, 1.932]} />
        <mesh name="Painting" geometry={nodes.Painting.geometry} material={materials.paint1} position={[1.846, 3.206, -4.091]} rotation={[Math.PI / 2, 0, 0]} scale={[-4.063, -2.219, -2.219]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.007']} position={[-0.354, 2.543, 4.715]} rotation={[Math.PI / 2, 0, -0.043]} scale={[0.701, 0.414, 0.42]} />
        <mesh name="underneath1" geometry={nodes.underneath1.geometry} material={materials['Black plastic']} position={[0.462, 1.133, -1.711]} rotation={[0, 1.064, 0]} scale={[0.069, 0.082, 0.082]} />
        <mesh name="switch2" geometry={nodes.switch2.geometry} material={materials.METALIC} position={[-0.258, 1.264, -1.674]} rotation={[-1.531, 0.88, 1.51]} scale={[0.003, 0.019, 0.006]} />
        <mesh name="switch1" geometry={nodes.switch1.geometry} material={materials['white plastic']} position={[-0.275, 1.284, -1.676]} rotation={[-0.872, 0.731, 1.025]} scale={0.02} />
        <mesh name="switch_plastic" geometry={nodes.switch_plastic.geometry} material={materials['white plastic']} position={[-0.244, 1.257, -1.673]} rotation={[0, -0.023, 0]} scale={[0.25, 0.491, 0.106]} />
        <mesh name="StringhE" geometry={nodes.StringhE.geometry} material={materials['Material.010']} position={[0.118, 1.283, -1.787]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
        <mesh name="StringG" geometry={nodes.StringG.geometry} material={materials['Material.019']} position={[0.151, 1.283, -1.846]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
        <mesh name="Stringend" geometry={nodes.Stringend.geometry} material={materials.METALIC} position={[-0.279, 1.257, -2.089]} rotation={[0, 1.064, 0]} scale={[0.151, 0.064, 0.064]} />
        <mesh name="Stringe" geometry={nodes.Stringe.geometry} material={materials['Material.021']} position={[0.204, 1.283, -1.941]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
        <mesh name="StringD" geometry={nodes.StringD.geometry} material={materials['Material.022']} position={[0.168, 1.283, -1.876]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
        <mesh name="StringB" geometry={nodes.StringB.geometry} material={materials['Material.023']} position={[2.289, 1.261, -0.64]} rotation={[0, 1.064, 0]} scale={3.621} />
        <mesh name="StringA" geometry={nodes.StringA.geometry} material={materials['Material.024']} position={[0.186, 1.283, -1.908]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
        <mesh name="screwy" geometry={nodes.screwy.geometry} material={materials.METALIC} position={[-0.671, 1.197, -2.324]} rotation={[-Math.PI / 2, 0, 1.064]} scale={0.14} />
        <mesh name="screwx" geometry={nodes.screwx.geometry} material={materials['Black plastic']} position={[1.91, 1.241, -0.893]} rotation={[0, 1.064, 0]} scale={0.059} />
        <mesh name="screw5" geometry={nodes.screw5.geometry} material={materials.METALIC} position={[0.99, 1.192, -1.835]} rotation={[-Math.PI / 2, 0, -2.431]} scale={0.132} />
        <mesh name="screw2" geometry={nodes.screw2.geometry} material={materials['Black plastic']} position={[-0.793, 1.193, -1.827]} rotation={[-Math.PI / 2, 0, 1.809]} scale={0.067} />
        <mesh name="screw" geometry={nodes.screw.geometry} material={materials['Black plastic']} position={[-0.805, 1.192, -1.962]} rotation={[-Math.PI / 2, 0, 1.522]} scale={0.067} />
        <mesh name="plate" geometry={nodes.plate.geometry} material={materials['Black plastic']} position={[-0.093, 1.264, -2.005]} rotation={[0, 1.064, 0]} scale={[0.131, 0.131, 0.074]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['white plastic']} position={[-0.162, 1.135, -2.03]} rotation={[0, 1.064, 0]} scale={[0.173, 0.221, 0.258]} />
        <group name="plaatGroot" position={[-0.018, 1.264, -1.812]} rotation={[0, 0.697, 0]} scale={0.062}>
          <mesh name="NurbsPath005_1" geometry={nodes.NurbsPath005_1.geometry} material={materials['white plastic']} />
          <mesh name="NurbsPath005_2" geometry={nodes.NurbsPath005_2.geometry} material={materials['Black plastic']} />
        </group>
        <mesh name="pickup4" geometry={nodes.pickup4.geometry} material={materials['white plastic']} position={[-0.12, 1.249, -2.02]} rotation={[0, 1.064, 0]} scale={0.04} />
        <mesh name="pickup3" geometry={nodes.pickup3.geometry} material={materials['white plastic']} position={[-0.063, 1.249, -1.989]} rotation={[0, 1.064, 0]} scale={0.04} />
        <mesh name="pickup2" geometry={nodes.pickup2.geometry} material={materials['white plastic']} position={[0.096, 1.249, -1.9]} rotation={[0, 1.064, 0]} scale={0.041} />
        <mesh name="pickup1" geometry={nodes.pickup1.geometry} material={materials['white plastic']} position={[0.27, 1.249, -1.807]} rotation={[0, 1.064, 0]} scale={0.041} />
        <group name="mainframe" position={[-0.073, 1.193, -1.989]} rotation={[Math.PI, -1.064, Math.PI]} scale={0.148}>
          <mesh name="NurbsPath_1" geometry={nodes.NurbsPath_1.geometry} material={materials['Material.025']} />
          <mesh name="NurbsPath_2" geometry={nodes.NurbsPath_2.geometry} material={materials['Black plastic']} />
        </group>
        <mesh name="magnetos3" geometry={nodes.magnetos3.geometry} material={materials.METALIC} position={[-0.076, 1.267, -2.102]} rotation={[0, 1.064, 0]} scale={0.01} />
        <mesh name="magnetos2" geometry={nodes.magnetos2.geometry} material={materials.METALIC} position={[-0.038, 1.267, -2.037]} rotation={[0, 1.064, 0]} scale={0.01} />
        <mesh name="magnetos1" geometry={nodes.magnetos1.geometry} material={materials.METALIC} position={[0.121, 1.271, -1.949]} rotation={[0, 1.064, 0]} scale={0.011} />
        <mesh name="magnetos0" geometry={nodes.magnetos0.geometry} material={materials.METALIC} position={[0.222, 1.271, -1.723]} rotation={[0, 1.064, 0]} scale={0.011} />
        <mesh name="knobs001" geometry={nodes.knobs001.geometry} material={materials['white plastic']} position={[-0.45, 1.295, -1.699]} rotation={[-Math.PI, -1.064, 0]} scale={0.03} />
        <mesh name="knobs" geometry={nodes.knobs.geometry} material={materials['white plastic']} position={[-0.27, 1.295, -1.808]} rotation={[-Math.PI, -1.064, 0]} scale={0.03} />
        <mesh name="knob005" geometry={nodes.knob005.geometry} material={materials.METALIC} position={[2.357, 1.267, -0.58]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="knob004" geometry={nodes.knob004.geometry} material={materials.METALIC} position={[2.296, 1.267, -0.644]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="knob003" geometry={nodes.knob003.geometry} material={materials.METALIC} position={[2.235, 1.267, -0.709]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="knob002" geometry={nodes.knob002.geometry} material={materials.METALIC} position={[2.175, 1.267, -0.773]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="knob001" geometry={nodes.knob001.geometry} material={materials.METALIC} position={[2.116, 1.267, -0.836]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="knob" geometry={nodes.knob.geometry} material={materials.METALIC} position={[2.055, 1.267, -0.901]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="handle2" geometry={nodes.handle2.geometry} material={materials.METALIC} position={[0.983, 1.192, -1.842]} rotation={[Math.PI / 2, 0, 2.431]} scale={0.015} />
        <mesh name="handle" geometry={nodes.handle.geometry} material={materials.METALIC} position={[-0.661, 1.197, -2.319]} rotation={[Math.PI / 2, 0, -1.064]} scale={0.016} />
        <group name="hals2" position={[2.235, 1.195, -0.767]} rotation={[-Math.PI, 0.813, -Math.PI]} scale={0.075}>
          <mesh name="NurbsPath002_1" geometry={nodes.NurbsPath002_1.geometry} material={materials['white plastic']} />
          <mesh name="NurbsPath002_2" geometry={nodes.NurbsPath002_2.geometry} material={materials['Material.027']} />
        </group>
        <group name="hals" position={[1.048, 1.269, -1.373]} rotation={[-Math.PI, -1.064, 0]} scale={[0.362, 3.621, 1.086]}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.027']} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['Black plastic']} />
          <mesh name="Plane010_2" geometry={nodes.Plane010_2.geometry} material={materials.METALIC} />
        </group>
        <mesh name="draaidingcenter1005" geometry={nodes.draaidingcenter1005.geometry} material={materials.METALIC} position={[2.055, 1.163, -0.904]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
        <mesh name="draaidingcenter1004" geometry={nodes.draaidingcenter1004.geometry} material={materials.METALIC} position={[2.115, 1.163, -0.841]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
        <mesh name="draaidingcenter1003" geometry={nodes.draaidingcenter1003.geometry} material={materials.METALIC} position={[2.174, 1.163, -0.775]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
        <mesh name="draaidingcenter1002" geometry={nodes.draaidingcenter1002.geometry} material={materials.METALIC} position={[2.235, 1.163, -0.708]} rotation={[Math.PI, -0.785, Math.PI]} scale={3.557} />
        <mesh name="draaidingcenter1001" geometry={nodes.draaidingcenter1001.geometry} material={materials.METALIC} position={[2.298, 1.163, -0.643]} rotation={[Math.PI, -0.797, Math.PI]} scale={3.557} />
        <mesh name="draaidingcenter1" geometry={nodes.draaidingcenter1.geometry} material={materials.METALIC} position={[2.36, 1.163, -0.581]} rotation={[Math.PI, -0.801, Math.PI]} scale={3.557} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[2.055, 1.262, -0.9]} rotation={[0, 1.064, 0]} scale={-0.01} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.METALIC} position={[-0.316, 1.277, -2.023]} rotation={[-0.054, 1.063, 0.052]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials.METALIC} position={[-0.298, 1.277, -2.056]} rotation={[-0.056, 1.076, 0.053]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials.METALIC} position={[-0.279, 1.277, -2.088]} rotation={[-0.054, 1.058, 0.051]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials.METALIC} position={[-0.263, 1.277, -2.121]} rotation={[-0.054, 1.058, 0.051]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials.METALIC} position={[-0.242, 1.277, -2.152]} rotation={[-0.052, 1.042, 0.049]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials.METALIC} position={[-0.225, 1.277, -2.186]} rotation={[-0.052, 1.042, 0.049]} scale={[0.018, 0.009, 0.037]} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[-0.235, 1.267, -1.674]} rotation={[0, 1.543, 0]} scale={[0.004, 0.171, 0.044]} />
        <mesh name="Circle059" geometry={nodes.Circle059.geometry} material={nodes.Circle059.material} position={[1.576, 1.274, -1.08]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle058" geometry={nodes.Circle058.geometry} material={nodes.Circle058.material} position={[1.381, 1.274, -1.188]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle057" geometry={nodes.Circle057.geometry} material={nodes.Circle057.material} position={[1.207, 1.274, -1.285]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle056" geometry={nodes.Circle056.geometry} material={nodes.Circle056.material} position={[1.048, 1.274, -1.373]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle055" geometry={nodes.Circle055.geometry} material={nodes.Circle055.material} position={[0.87, 1.274, -1.529]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle054" geometry={nodes.Circle054.geometry} material={nodes.Circle054.material} position={[0.821, 1.274, -1.44]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle053" geometry={nodes.Circle053.geometry} material={nodes.Circle053.material} position={[0.675, 1.274, -1.58]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle052" geometry={nodes.Circle052.geometry} material={nodes.Circle052.material} position={[0.578, 1.274, -1.634]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle051" geometry={nodes.Circle051.geometry} material={nodes.Circle051.material} position={[0.492, 1.274, -1.682]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle050" geometry={nodes.Circle050.geometry} material={nodes.Circle050.material} position={[0.412, 1.274, -1.726]} rotation={[0, 1.064, 0]} scale={0.047} />
        <mesh name="Circle049" geometry={nodes.Circle049.geometry} material={materials['METALIC.014']} position={[-0.372, 1.273, -2.055]} rotation={[-1.578, -0.012, 1.069]} scale={0.116} />
        <mesh name="Circle048" geometry={nodes.Circle048.geometry} material={materials['METALIC.013']} position={[-0.354, 1.273, -2.088]} rotation={[-1.578, -0.012, 1.069]} scale={0.116} />
        <mesh name="Circle047" geometry={nodes.Circle047.geometry} material={materials['METALIC.012']} position={[-0.335, 1.273, -2.121]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
        <mesh name="Circle046" geometry={nodes.Circle046.geometry} material={materials['METALIC.011']} position={[-0.318, 1.273, -2.153]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
        <mesh name="Circle045" geometry={nodes.Circle045.geometry} material={materials['METALIC.010']} position={[-0.299, 1.273, -2.186]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
        <mesh name="Circle044" geometry={nodes.Circle044.geometry} material={materials['METALIC.009']} position={[-0.281, 1.273, -2.219]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
        <mesh name="Circle043" geometry={nodes.Circle043.geometry} material={materials['METALIC.007']} position={[-0.252, 1.265, -1.986]} rotation={[0, 1.299, 0]} scale={0.115} />
        <mesh name="Circle042" geometry={nodes.Circle042.geometry} material={materials['METALIC.006']} position={[-0.233, 1.265, -2.02]} rotation={[0, 0.066, 0]} scale={0.115} />
        <mesh name="Circle041" geometry={nodes.Circle041.geometry} material={materials['METALIC.005']} position={[-0.215, 1.265, -2.052]} rotation={[0, -0.555, 0]} scale={0.115} />
        <mesh name="Circle040" geometry={nodes.Circle040.geometry} material={materials['METALIC.004']} position={[-0.215, 1.262, -2.052]} rotation={[0, -0.555, 0]} scale={0.115} />
        <mesh name="Circle039" geometry={nodes.Circle039.geometry} material={materials['METALIC.003']} position={[-0.198, 1.265, -2.083]} rotation={[0, -0.555, 0]} scale={0.115} />
        <mesh name="Circle038" geometry={nodes.Circle038.geometry} material={materials['METALIC.002']} position={[-0.18, 1.265, -2.116]} rotation={[Math.PI, -0.186, Math.PI]} scale={0.115} />
        <mesh name="Circle037" geometry={nodes.Circle037.geometry} material={materials.METALIC} position={[-0.052, 1.124, -2.137]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle036" geometry={nodes.Circle036.geometry} material={materials['Material.031']} position={[-0.272, 1.124, -1.92]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle035" geometry={nodes.Circle035.geometry} material={materials.METALIC} position={[-0.301, 1.124, -2.275]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle034" geometry={nodes.Circle034.geometry} material={materials.METALIC} position={[-0.445, 1.124, -2.016]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle033" geometry={nodes.Circle033.geometry} material={materials.METALIC} position={[-0.024, 1.124, -1.782]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle032" geometry={nodes.Circle032.geometry} material={materials.METALIC} position={[0.12, 1.124, -2.041]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
        <mesh name="Circle031" geometry={nodes.Circle031.geometry} material={materials.METALIC} position={[0.377, 1.123, -1.697]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
        <mesh name="Circle030" geometry={nodes.Circle030.geometry} material={materials.METALIC} position={[0.429, 1.123, -1.791]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
        <mesh name="Circle029" geometry={nodes.Circle029.geometry} material={materials.METALIC} position={[0.547, 1.123, -1.726]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
        <mesh name="Circle028" geometry={nodes.Circle028.geometry} material={materials.METALIC} position={[0.494, 1.123, -1.631]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
        <mesh name="Circle027" geometry={nodes.Circle027.geometry} material={materials.METALIC} position={[2.153, 1.179, -0.96]} rotation={[-1.035, 0.31, -0.974]} scale={0.078} />
        <mesh name="Circle026" geometry={nodes.Circle026.geometry} material={materials.METALIC} position={[2.214, 1.179, -0.896]} rotation={[-0.937, 0.47, -0.984]} scale={0.078} />
        <mesh name="Circle025" geometry={nodes.Circle025.geometry} material={materials.METALIC} position={[2.273, 1.179, -0.831]} rotation={[0.948, 0.477, -2.062]} scale={0.078} />
        <mesh name="Circle024" geometry={nodes.Circle024.geometry} material={materials.METALIC} position={[2.331, 1.179, -0.767]} rotation={[0.604, 0.654, -1.916]} scale={0.078} />
        <mesh name="Circle023" geometry={nodes.Circle023.geometry} material={materials.METALIC} position={[2.394, 1.179, -0.703]} rotation={[-0.17, 0.734, -1.442]} scale={0.078} />
        <mesh name="Circle022" geometry={nodes.Circle022.geometry} material={materials.METALIC} position={[2.441, 1.177, -0.628]} rotation={[0.895, 0.472, -2.113]} scale={0.078} />
        <mesh name="Circle021" geometry={nodes.Circle021.geometry} material={materials.METALIC} position={[-0.803, 1.195, -1.892]} rotation={[-1.72, -0.017, 1.689]} scale={0.017} />
        <mesh name="Circle020" geometry={nodes.Circle020.geometry} material={materials.METALIC} position={[-0.805, 1.195, -1.892]} rotation={[Math.PI / 2, 0, -1.671]} scale={0.018} />
        <mesh name="Circle019" geometry={nodes.Circle019.geometry} material={materials.METALIC} position={[-0.578, 1.262, -1.683]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle018" geometry={nodes.Circle018.geometry} material={materials.METALIC} position={[-0.352, 1.262, -1.625]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle017" geometry={nodes.Circle017.geometry} material={materials.METALIC} position={[-0.309, 1.262, -1.675]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle016" geometry={nodes.Circle016.geometry} material={materials.METALIC} position={[-0.162, 1.262, -1.672]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle015" geometry={nodes.Circle015.geometry} material={materials.METALIC} position={[-0.088, 1.261, -1.596]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle014" geometry={nodes.Circle014.geometry} material={materials.METALIC} position={[0.088, 1.261, -1.445]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={materials.METALIC} position={[0.023, 1.262, -1.776]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials.METALIC} position={[-0.162, 1.262, -1.878]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle011" geometry={nodes.Circle011.geometry} material={materials.METALIC} position={[-0.022, 1.262, -2.132]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle010" geometry={nodes.Circle010.geometry} material={materials.METALIC} position={[-0.294, 1.261, -1.914]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials.METALIC} position={[-0.117, 1.262, -2.212]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials['METALIC.001']} position={[-0.161, 1.265, -2.149]} rotation={[0, 1.064, 0]} scale={0.115} />
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.METALIC} position={[0.153, 1.262, -2.089]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials.METALIC} position={[0.162, 1.262, -2.026]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.METALIC} position={[0.203, 1.262, -2.033]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials.METALIC} position={[0.517, 1.262, -1.861]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials.METALIC} position={[0.334, 1.262, -1.931]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials.METALIC} position={[0.197, 1.262, -1.682]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle060" geometry={nodes.Circle060.geometry} material={materials.METALIC} position={[0.193, 1.262, -1.616]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.METALIC} position={[0.243, 1.262, -1.308]} rotation={[0, 1.064, 0]} scale={0.106} />
        <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.036']} position={[-2.323, 1.997, -3.499]} rotation={[-Math.PI / 2, 0, 0.714]} scale={-0.032} />
        <group name="Roundcube003" position={[-3.14, 2.361, -3.203]} rotation={[0, -0.857, 0]} scale={[0.313, 0.263, 0.921]}>
          <mesh name="Roundcube003_1" geometry={nodes.Roundcube003_1.geometry} material={materials['Marshall pic']} />
          <mesh name="Roundcube003_2" geometry={nodes.Roundcube003_2.geometry} material={materials['Black leather']} />
          <mesh name="Roundcube003_3" geometry={nodes.Roundcube003_3.geometry} material={materials['Corner metal']} />
          <mesh name="Roundcube003_4" geometry={nodes.Roundcube003_4.geometry} material={materials['Material.037']} />
          <mesh name="Roundcube003_5" geometry={nodes.Roundcube003_5.geometry} material={materials['Material.038']} />
          <mesh name="Roundcube003_6" geometry={nodes.Roundcube003_6.geometry} material={materials['Material.039']} />
          <mesh name="Roundcube003_7" geometry={nodes.Roundcube003_7.geometry} material={materials['Material.040']} />
          <mesh name="Roundcube003_8" geometry={nodes.Roundcube003_8.geometry} material={materials['Material.041']} />
          <mesh name="Roundcube003_9" geometry={nodes.Roundcube003_9.geometry} material={materials['Material.042']} />
          <mesh name="Roundcube003_10" geometry={nodes.Roundcube003_10.geometry} material={materials['Material.036']} />
        </group>
        <group name="Roundcube001" position={[-3.136, 1.109, -3.205]} rotation={[0, -0.857, 0]} scale={[0.337, 0.987, 0.93]}>
          <mesh name="Roundcube001_1" geometry={nodes.Roundcube001_1.geometry} material={materials['Material.043']} />
          <mesh name="Roundcube001_2" geometry={nodes.Roundcube001_2.geometry} material={materials['Material.044']} />
          <mesh name="Roundcube001_3" geometry={nodes.Roundcube001_3.geometry} material={materials['Corner metal']} />
          <mesh name="Roundcube001_4" geometry={nodes.Roundcube001_4.geometry} material={materials['Material.047']} />
          <mesh name="Roundcube001_5" geometry={nodes.Roundcube001_5.geometry} material={materials['Back ']} />
        </group>
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Black metall']} position={[-2.274, 6.132, -2.056]} scale={[0.017, 0.01, 0.017]} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.LIght} position={[-2.274, 6.023, -2.057]} rotation={[-Math.PI, 0, 0]} scale={0.054} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Black metal']} position={[-2.275, 5.798, -2.057]} scale={0.325} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Black metall.001']} position={[-2.275, 5.798, -2.057]} scale={0.324} />
        <group name="SnakePlant_01" position={[3.639, 0.059, 1.99]} rotation={[-Math.PI, 1.463, -Math.PI]} scale={3.642}>
          <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials.Pot_02} />
          <mesh name="Cylinder014_1" geometry={nodes.Cylinder014_1.geometry} material={materials.Soil} />
          <mesh name="Cylinder014_2" geometry={nodes.Cylinder014_2.geometry} material={materials.SnakePlant_Leave} />
        </group>
        <group name="Palm_03" position={[-1.482, 1.839, 4.639]} scale={1.326}>
          <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.Pot_03} />
          <mesh name="Cylinder015_1" geometry={nodes.Cylinder015_1.geometry} material={materials.Soil} />
          <mesh name="Cylinder015_2" geometry={nodes.Cylinder015_2.geometry} material={materials.Palm_Leaves} />
          <mesh name="Cylinder015_3" geometry={nodes.Cylinder015_3.geometry} material={materials.Stalk} />
        </group>
        <group name="SnakePlant_02" position={[3.962, 3.42, 4.467]} rotation={[-Math.PI, 0.242, -Math.PI]}>
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.SnakePlant_Leave} />
          <mesh name="Plane029_1" geometry={nodes.Plane029_1.geometry} material={materials.Pot_01} />
          <mesh name="Plane029_2" geometry={nodes.Plane029_2.geometry} material={materials.Soil} />
        </group>
        <group name="Epipremium001" position={[-4.539, 0.117, 0.558]} scale={3.78}>
          <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Soil} />
          <mesh name="Cylinder016_1" geometry={nodes.Cylinder016_1.geometry} material={materials.Pot_02} />
          <mesh name="Cylinder016_2" geometry={nodes.Cylinder016_2.geometry} material={materials.Coconut} />
          <mesh name="Cylinder016_3" geometry={nodes.Cylinder016_3.geometry} material={materials.Epipremium_01} />
          <mesh name="Cylinder016_4" geometry={nodes.Cylinder016_4.geometry} material={materials.Epipremium_02} />
          <mesh name="Cylinder016_5" geometry={nodes.Cylinder016_5.geometry} material={materials.Stalk} />
        </group>
        <mesh name="Base" geometry={nodes.Base.geometry} material={materials.Metalic} position={[4.066, 0.624, -2.077]} scale={[1, 0.905, 1.135]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.012']} position={[-1.013, 0.631, -2.077]} />
        <mesh name="Base001" geometry={nodes.Base001.geometry} material={materials.Metalic} position={[4.066, 0.624, -2.077]} scale={[1, 0.905, 1.135]} />
        <mesh name="Head" geometry={nodes.Head.geometry} material={materials.Metalic} position={[-1, 0.493, -1.97]} />
        <mesh name="Pillow_left" geometry={nodes.Pillow_left.geometry} material={materials['Material.002']} position={[3.074, 1.551, -3.06]} rotation={[0, 0.3, 0]} scale={[0.433, 0.826, 0.776]} />
        <mesh name="Pillow_right" geometry={nodes.Pillow_right.geometry} material={materials['Material.002']} position={[3.698, 1.66, -1.318]} rotation={[0, 0, 0.685]} scale={[0.415, 0.845, 0.776]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[2.998, 3.532, 5.382]} scale={0.178} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.003']} position={[2.998, 2.596, 3.942]} scale={0.178} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.003']} position={[2.998, 1.721, 5.336]} scale={0.178} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.014']} position={[3.867, 2.718, 3.035]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.013']} position={[3.867, 2.718, 2.773]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.017']} position={[3.867, 2.718, 3.123]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.016']} position={[3.867, 2.718, 2.948]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.015']} position={[3.867, 2.718, 2.86]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.013']} position={[3.96, 3.693, 3.423]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.017']} position={[3.946, 3.712, 3.773]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.020']} position={[3.926, 3.693, 3.685]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.020']} position={[3.946, 3.683, 3.597]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.015']} position={[3.946, 3.731, 3.51]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.013']} position={[3.96, 3.693, 3.869]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.017']} position={[3.946, 3.712, 4.219]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.020']} position={[3.926, 3.693, 4.131]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.020']} position={[3.946, 3.683, 4.044]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.015']} position={[3.946, 3.731, 3.956]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Material.013']} position={[3.96, 1.874, 3.707]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Material.017']} position={[3.946, 1.894, 4.057]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.020']} position={[3.926, 1.874, 3.969]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['Material.020']} position={[3.946, 1.865, 3.882]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Material.015']} position={[3.946, 1.913, 3.794]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['Material.013']} position={[3.96, 1.874, 4.153]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['Material.017']} position={[3.946, 1.894, 4.503]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['Material.020']} position={[3.926, 1.874, 4.415]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['Material.020']} position={[3.946, 1.865, 4.328]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['Material.015']} position={[3.946, 1.913, 4.24]} scale={[0.146, 0.103, 0.146]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.011']} position={[3.937, 2.66, 3.015]} scale={0.109} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.018']} position={[3.94, 2.671, 2.543]} rotation={[-0.095, -0.238, -0.518]} scale={0.119} />
        <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['Material.034']} position={[3.956, 1.791, 3.46]} scale={0.187} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['Material.032']} position={[-0.348, 1.883, 4.107]} scale={0.289} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Material.033']} position={[-0.413, 1.885, 4.802]} scale={0.35} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.026']} position={[-0.438, 1.227, 4.362]} />
        <mesh name="Cadeira_escritorio" geometry={nodes.Cadeira_escritorio.geometry} material={materials['Material.028']} position={[-0.306, 1.191, 3.181]} rotation={[1.618, 0.01, 0.219]} scale={[-0.654, -0.496, -0.061]}>
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[1.079, 1.393, 11.019]} rotation={[0.867, 0.49, 1.907]} scale={[-0.393, -0.038, -0.098]} />
          <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.028']} position={[0, 1.334, 10.298]} rotation={[1.092, 0, 0]} scale={[0.818, 4.652, 0.181]} />
          <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Material.028']} position={[-1.04, 0.219, 9.988]} rotation={[-0.25, 0, 0]} scale={[0.149, 0.657, 0.82]} />
          <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Material.028']} position={[1.045, 0.219, 9.988]} rotation={[-0.25, 0, 0]} scale={[0.149, 0.657, 0.82]} />
          <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Material.029']} position={[-1.005, 0.005, -14.829]} rotation={[-1.775, 0, -Math.PI]} scale={[0.077, 0.821, 0.109]} />
          <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Material.029']} position={[1.042, 0.004, -14.948]} rotation={[1.367, 0, -Math.PI]} scale={[-0.077, -0.821, -0.109]} />
          <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['Material.029']} position={[0.001, -1.37, -14.383]} rotation={[0.494, -1.333, 2.268]} scale={[-0.109, -0.821, -0.077]} />
          <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['Material.029']} position={[-0.014, 1.348, -15.361]} rotation={[-2.648, 1.333, 0.873]} scale={[-0.109, -0.821, -0.077]} />
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.001, 0.06, -0.548]} rotation={[1.367, 0, Math.PI]} scale={[-0.127, -1.355, -0.179]} />
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.030']} position={[0.496, 0.077, -0.5]} rotation={[-1.789, 0.182, 1.725]} scale={[-0.379, -0.46, -0.05]} />
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.030']} position={[-1.08, 0.116, 5.917]} rotation={[-1.775, 0, Math.PI]} scale={[-0.035, -4.912, -0.05]} />
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.030']} position={[-0.003, 0.453, -0.647]} rotation={[1.287, -1.386, -1.667]} scale={[-0.379, -0.65, -0.035]} />
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.030']} position={[0.001, 0.048, -4.541]} rotation={[1.367, 0, -Math.PI]} scale={[-0.085, -3.68, -0.121]} />
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Material.029']} position={[0.002, 0.017, -9.016]} rotation={[1.367, 0, -Math.PI]} scale={[-0.143, -1.53, -0.203]} />
          <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.029']} position={[0.971, -0.002, -16.838]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['Material.029']} position={[0.447, -0.002, -16.838]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials['Material.029']} position={[-0.543, -0.002, -16.838]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials['Material.029']} position={[-1.032, -0.002, -16.838]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials['Material.029']} position={[-0.054, -1.344, -16.312]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials['Material.029']} position={[-0.054, -0.808, -16.522]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={materials['Material.029']} position={[-0.054, 1.304, -17.35]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
          <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials['Material.029']} position={[-0.054, 0.672, -17.102]} rotation={[1.367, 0, -Math.PI]} scale={[0.084, 0.895, 0.118]} />
        </mesh>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.006']} position={[0.204, 1.002, -5.566]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.008']} position={[-3.947, 1.002, 0]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[3.827, 1.002, 0.052]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[-0.729, 0.082, 0.568]} scale={[3.3, 1.161, 2.524]} />
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
