apiVersion: v1
kind: Secret
metadata:
  name: db-connection

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19vMEN1b3NyMWJXcnRHMUkyUWFrQHByb2plY3RhLWRvLXVzZXItMTYzNzcyMTAtMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9Qcm9qZWN0QT9zc2xtb2RlPXJlcXVpcmUK