/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\models\room\untitled.gltf -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    underneath1: THREE.Mesh
    switch2: THREE.Mesh
    switch1: THREE.Mesh
    switch_plastic: THREE.Mesh
    StringhE: THREE.Mesh
    StringG: THREE.Mesh
    Stringend: THREE.Mesh
    Stringe: THREE.Mesh
    StringD: THREE.Mesh
    StringB: THREE.Mesh
    StringA: THREE.Mesh
    screwy: THREE.Mesh
    screwx: THREE.Mesh
    screw5: THREE.Mesh
    screw2: THREE.Mesh
    screw: THREE.Mesh
    plate: THREE.Mesh
    Plane003: THREE.Mesh
    NurbsPath005_1: THREE.Mesh
    NurbsPath005_2: THREE.Mesh
    pickup4: THREE.Mesh
    pickup3: THREE.Mesh
    pickup2: THREE.Mesh
    pickup1: THREE.Mesh
    NurbsPath_1: THREE.Mesh
    NurbsPath_2: THREE.Mesh
    magnetos3: THREE.Mesh
    magnetos2: THREE.Mesh
    magnetos1: THREE.Mesh
    magnetos0: THREE.Mesh
    knobs001: THREE.Mesh
    knobs: THREE.Mesh
    knob005: THREE.Mesh
    knob004: THREE.Mesh
    knob003: THREE.Mesh
    knob002: THREE.Mesh
    knob001: THREE.Mesh
    knob: THREE.Mesh
    handle2: THREE.Mesh
    handle: THREE.Mesh
    NurbsPath002_1: THREE.Mesh
    NurbsPath002_2: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane010_2: THREE.Mesh
    draaidingcenter1005: THREE.Mesh
    draaidingcenter1004: THREE.Mesh
    draaidingcenter1003: THREE.Mesh
    draaidingcenter1002: THREE.Mesh
    draaidingcenter1001: THREE.Mesh
    draaidingcenter1: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cube048: THREE.Mesh
    Cube047: THREE.Mesh
    Cube046: THREE.Mesh
    Cube045: THREE.Mesh
    Cube044: THREE.Mesh
    Cube043: THREE.Mesh
    Cube022: THREE.Mesh
    Circle060: THREE.Mesh
    Circle059: THREE.Mesh
    Circle058: THREE.Mesh
    Circle057: THREE.Mesh
    Circle056: THREE.Mesh
    Circle055: THREE.Mesh
    Circle054: THREE.Mesh
    Circle053: THREE.Mesh
    Circle052: THREE.Mesh
    Circle051: THREE.Mesh
    Circle050: THREE.Mesh
    Circle049: THREE.Mesh
    Circle048: THREE.Mesh
    Circle047: THREE.Mesh
    Circle046: THREE.Mesh
    Circle045: THREE.Mesh
    Circle044: THREE.Mesh
    Circle043: THREE.Mesh
    Circle042: THREE.Mesh
    Circle041: THREE.Mesh
    Circle040: THREE.Mesh
    Circle039: THREE.Mesh
    Circle038: THREE.Mesh
    Circle037: THREE.Mesh
    Circle036: THREE.Mesh
    Circle035: THREE.Mesh
    Circle034: THREE.Mesh
    Circle033: THREE.Mesh
    Circle032: THREE.Mesh
    Circle031: THREE.Mesh
    Circle030: THREE.Mesh
    Circle029: THREE.Mesh
    Circle028: THREE.Mesh
    Circle027: THREE.Mesh
    Circle026: THREE.Mesh
    Circle025: THREE.Mesh
    Circle024: THREE.Mesh
    Circle023: THREE.Mesh
    Circle022: THREE.Mesh
    Circle021: THREE.Mesh
    Circle020: THREE.Mesh
    Circle019: THREE.Mesh
    Circle018: THREE.Mesh
    Circle017: THREE.Mesh
    Circle016: THREE.Mesh
    Circle015: THREE.Mesh
    Circle014: THREE.Mesh
    Circle013: THREE.Mesh
    Circle012: THREE.Mesh
    Circle011: THREE.Mesh
    Circle010: THREE.Mesh
    Circle009: THREE.Mesh
    Circle008: THREE.Mesh
    Circle007: THREE.Mesh
    Circle006: THREE.Mesh
    Circle005: THREE.Mesh
    Circle004: THREE.Mesh
    Circle003: THREE.Mesh
    Circle002: THREE.Mesh
    Circle: THREE.Mesh
  }
  materials: {
    ['Black plastic']: THREE.MeshStandardMaterial
    METALIC: THREE.MeshStandardMaterial
    ['white plastic']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['METALIC.014']: THREE.MeshStandardMaterial
    ['METALIC.013']: THREE.MeshStandardMaterial
    ['METALIC.012']: THREE.MeshStandardMaterial
    ['METALIC.011']: THREE.MeshStandardMaterial
    ['METALIC.010']: THREE.MeshStandardMaterial
    ['METALIC.009']: THREE.MeshStandardMaterial
    ['METALIC.007']: THREE.MeshStandardMaterial
    ['METALIC.006']: THREE.MeshStandardMaterial
    ['METALIC.005']: THREE.MeshStandardMaterial
    ['METALIC.004']: THREE.MeshStandardMaterial
    ['METALIC.003']: THREE.MeshStandardMaterial
    ['METALIC.002']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['METALIC.001']: THREE.MeshStandardMaterial
  }
}



export function Guitar(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/room/untitled.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.underneath1.geometry} material={materials['Black plastic']} position={[0.462, 1.132, -1.711]} rotation={[0, 1.064, 0]} scale={[0.069, 0.082, 0.082]} />
      <mesh geometry={nodes.switch2.geometry} material={materials.METALIC} position={[-0.258, 1.263, -1.674]} rotation={[-1.531, 0.88, 1.51]} scale={[0.003, 0.019, 0.006]} />
      <mesh geometry={nodes.switch1.geometry} material={materials['white plastic']} position={[-0.275, 1.283, -1.676]} rotation={[-0.872, 0.731, 1.025]} scale={0.02} />
      <mesh geometry={nodes.switch_plastic.geometry} material={materials['white plastic']} position={[-0.244, 1.256, -1.673]} rotation={[0, -0.023, 0]} scale={[0.25, 0.491, 0.106]} />
      <mesh geometry={nodes.StringhE.geometry} material={materials['Material.010']} position={[0.118, 1.282, -1.787]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
      <mesh geometry={nodes.StringG.geometry} material={materials['Material.019']} position={[0.151, 1.282, -1.846]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
      <mesh geometry={nodes.Stringend.geometry} material={materials.METALIC} position={[-0.279, 1.257, -2.089]} rotation={[0, 1.064, 0]} scale={[0.151, 0.064, 0.064]} />
      <mesh geometry={nodes.Stringe.geometry} material={materials['Material.021']} position={[0.204, 1.282, -1.941]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
      <mesh geometry={nodes.StringD.geometry} material={materials['Material.022']} position={[0.168, 1.282, -1.876]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
      <mesh geometry={nodes.StringB.geometry} material={materials['Material.023']} position={[2.289, 1.261, -0.64]} rotation={[0, 1.064, 0]} scale={3.621} />
      <mesh geometry={nodes.StringA.geometry} material={materials['Material.024']} position={[0.186, 1.282, -1.908]} rotation={[-Math.PI, 0.506, -Math.PI]} scale={0.019} />
      <mesh geometry={nodes.screwy.geometry} material={materials.METALIC} position={[-0.671, 1.196, -2.324]} rotation={[-Math.PI / 2, 0, 1.064]} scale={0.14} />
      <mesh geometry={nodes.screwx.geometry} material={materials['Black plastic']} position={[1.91, 1.24, -0.893]} rotation={[0, 1.064, 0]} scale={0.059} />
      <mesh geometry={nodes.screw5.geometry} material={materials.METALIC} position={[0.99, 1.191, -1.835]} rotation={[-Math.PI / 2, 0, -2.431]} scale={0.132} />
      <mesh geometry={nodes.screw2.geometry} material={materials['Black plastic']} position={[-0.793, 1.192, -1.827]} rotation={[-Math.PI / 2, 0, 1.809]} scale={0.067} />
      <mesh geometry={nodes.screw.geometry} material={materials['Black plastic']} position={[-0.805, 1.192, -1.962]} rotation={[-Math.PI / 2, 0, 1.522]} scale={0.067} />
      <mesh geometry={nodes.plate.geometry} material={materials['Black plastic']} position={[-0.093, 1.263, -2.005]} rotation={[0, 1.064, 0]} scale={[0.131, 0.131, 0.074]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['white plastic']} position={[-0.162, 1.134, -2.03]} rotation={[0, 1.064, 0]} scale={[0.173, 0.221, 0.258]} />
      <group position={[-0.018, 1.263, -1.812]} rotation={[0, 0.697, 0]} scale={0.062}>
        <mesh geometry={nodes.NurbsPath005_1.geometry} material={materials['white plastic']} />
        <mesh geometry={nodes.NurbsPath005_2.geometry} material={materials['Black plastic']} />
      </group>
      <mesh geometry={nodes.pickup4.geometry} material={materials['white plastic']} position={[-0.12, 1.249, -2.02]} rotation={[0, 1.064, 0]} scale={0.04} />
      <mesh geometry={nodes.pickup3.geometry} material={materials['white plastic']} position={[-0.063, 1.249, -1.989]} rotation={[0, 1.064, 0]} scale={0.04} />
      <mesh geometry={nodes.pickup2.geometry} material={materials['white plastic']} position={[0.096, 1.248, -1.9]} rotation={[0, 1.064, 0]} scale={0.041} />
      <mesh geometry={nodes.pickup1.geometry} material={materials['white plastic']} position={[0.27, 1.248, -1.807]} rotation={[0, 1.064, 0]} scale={0.041} />
      <group position={[-0.073, 1.192, -1.989]} rotation={[Math.PI, -1.064, Math.PI]} scale={0.148}>
        <mesh geometry={nodes.NurbsPath_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.NurbsPath_2.geometry} material={materials['Black plastic']} />
      </group>
      <mesh geometry={nodes.magnetos3.geometry} material={materials.METALIC} position={[-0.076, 1.266, -2.102]} rotation={[0, 1.064, 0]} scale={0.01} />
      <mesh geometry={nodes.magnetos2.geometry} material={materials.METALIC} position={[-0.038, 1.266, -2.037]} rotation={[0, 1.064, 0]} scale={0.01} />
      <mesh geometry={nodes.magnetos1.geometry} material={materials.METALIC} position={[0.121, 1.27, -1.949]} rotation={[0, 1.064, 0]} scale={0.011} />
      <mesh geometry={nodes.magnetos0.geometry} material={materials.METALIC} position={[0.222, 1.27, -1.723]} rotation={[0, 1.064, 0]} scale={0.011} />
      <mesh geometry={nodes.knobs001.geometry} material={materials['white plastic']} position={[-0.45, 1.294, -1.699]} rotation={[-Math.PI, -1.064, 0]} scale={0.03} />
      <mesh geometry={nodes.knobs.geometry} material={materials['white plastic']} position={[-0.27, 1.294, -1.808]} rotation={[-Math.PI, -1.064, 0]} scale={0.03} />
      <mesh geometry={nodes.knob005.geometry} material={materials.METALIC} position={[2.357, 1.266, -0.58]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.knob004.geometry} material={materials.METALIC} position={[2.296, 1.266, -0.644]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.knob003.geometry} material={materials.METALIC} position={[2.235, 1.266, -0.709]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.knob002.geometry} material={materials.METALIC} position={[2.175, 1.266, -0.773]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.knob001.geometry} material={materials.METALIC} position={[2.116, 1.266, -0.836]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.knob.geometry} material={materials.METALIC} position={[2.055, 1.266, -0.901]} rotation={[0, 1.064, 0]} scale={[0.01, 0.011, 0.01]} />
      <mesh geometry={nodes.handle2.geometry} material={materials.METALIC} position={[0.983, 1.191, -1.842]} rotation={[Math.PI / 2, 0, 2.431]} scale={0.015} />
      <mesh geometry={nodes.handle.geometry} material={materials.METALIC} position={[-0.661, 1.196, -2.319]} rotation={[Math.PI / 2, 0, -1.064]} scale={0.016} />
      <group position={[2.235, 1.195, -0.767]} rotation={[-Math.PI, 0.813, -Math.PI]} scale={0.075}>
        <mesh geometry={nodes.NurbsPath002_1.geometry} material={materials['white plastic']} />
        <mesh geometry={nodes.NurbsPath002_2.geometry} material={materials['Material.027']} />
      </group>
      <group position={[1.048, 1.269, -1.373]} rotation={[-Math.PI, -1.064, 0]} scale={[0.362, 3.621, 1.086]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Black plastic']} />
        <mesh geometry={nodes.Plane010_2.geometry} material={materials.METALIC} />
      </group>
      <mesh geometry={nodes.draaidingcenter1005.geometry} material={materials.METALIC} position={[2.055, 1.162, -0.904]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.draaidingcenter1004.geometry} material={materials.METALIC} position={[2.115, 1.162, -0.841]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.draaidingcenter1003.geometry} material={materials.METALIC} position={[2.174, 1.162, -0.775]} rotation={[Math.PI, -0.753, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.draaidingcenter1002.geometry} material={materials.METALIC} position={[2.235, 1.162, -0.708]} rotation={[Math.PI, -0.785, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.draaidingcenter1001.geometry} material={materials.METALIC} position={[2.298, 1.162, -0.643]} rotation={[Math.PI, -0.797, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.draaidingcenter1.geometry} material={materials.METALIC} position={[2.36, 1.162, -0.581]} rotation={[Math.PI, -0.801, Math.PI]} scale={3.557} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[2.055, 1.261, -0.9]} rotation={[0, 1.064, 0]} scale={-0.01} />
      <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[-0.235, 1.266, -1.674]} rotation={[0, 1.543, 0]} scale={[0.004, 0.171, 0.044]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.METALIC} position={[-0.225, 1.276, -2.186]} rotation={[-0.052, 1.042, 0.049]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.METALIC} position={[-0.242, 1.276, -2.152]} rotation={[-0.052, 1.042, 0.049]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.METALIC} position={[-0.263, 1.276, -2.121]} rotation={[-0.054, 1.058, 0.051]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.METALIC} position={[-0.279, 1.276, -2.088]} rotation={[-0.054, 1.058, 0.051]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.METALIC} position={[-0.298, 1.276, -2.056]} rotation={[-0.056, 1.076, 0.053]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.METALIC} position={[-0.316, 1.276, -2.023]} rotation={[-0.054, 1.063, 0.052]} scale={[0.018, 0.009, 0.037]} />
      <mesh geometry={nodes.Circle060.geometry} material={materials.METALIC} position={[0.193, 1.261, -1.616]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle059.geometry} material={nodes.Circle059.material} position={[1.576, 1.274, -1.08]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle058.geometry} material={nodes.Circle058.material} position={[1.381, 1.274, -1.188]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle057.geometry} material={nodes.Circle057.material} position={[1.207, 1.274, -1.285]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle056.geometry} material={nodes.Circle056.material} position={[1.048, 1.274, -1.373]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle055.geometry} material={nodes.Circle055.material} position={[0.87, 1.274, -1.529]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle054.geometry} material={nodes.Circle054.material} position={[0.821, 1.274, -1.44]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle053.geometry} material={nodes.Circle053.material} position={[0.675, 1.274, -1.58]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle052.geometry} material={nodes.Circle052.material} position={[0.578, 1.274, -1.634]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle051.geometry} material={nodes.Circle051.material} position={[0.492, 1.274, -1.682]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle050.geometry} material={nodes.Circle050.material} position={[0.412, 1.274, -1.726]} rotation={[0, 1.064, 0]} scale={0.047} />
      <mesh geometry={nodes.Circle049.geometry} material={materials['METALIC.014']} position={[-0.372, 1.273, -2.055]} rotation={[-1.578, -0.012, 1.069]} scale={0.116} />
      <mesh geometry={nodes.Circle048.geometry} material={materials['METALIC.013']} position={[-0.354, 1.273, -2.088]} rotation={[-1.578, -0.012, 1.069]} scale={0.116} />
      <mesh geometry={nodes.Circle047.geometry} material={materials['METALIC.012']} position={[-0.335, 1.273, -2.121]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
      <mesh geometry={nodes.Circle046.geometry} material={materials['METALIC.011']} position={[-0.318, 1.273, -2.153]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
      <mesh geometry={nodes.Circle045.geometry} material={materials['METALIC.010']} position={[-0.299, 1.273, -2.186]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
      <mesh geometry={nodes.Circle044.geometry} material={materials['METALIC.009']} position={[-0.281, 1.273, -2.219]} rotation={[-1.578, -0.012, 1.064]} scale={0.116} />
      <mesh geometry={nodes.Circle043.geometry} material={materials['METALIC.007']} position={[-0.252, 1.264, -1.986]} rotation={[0, 1.299, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle042.geometry} material={materials['METALIC.006']} position={[-0.233, 1.264, -2.02]} rotation={[0, 0.066, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle041.geometry} material={materials['METALIC.005']} position={[-0.215, 1.264, -2.052]} rotation={[0, -0.555, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle040.geometry} material={materials['METALIC.004']} position={[-0.215, 1.261, -2.052]} rotation={[0, -0.555, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle039.geometry} material={materials['METALIC.003']} position={[-0.198, 1.264, -2.083]} rotation={[0, -0.555, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle038.geometry} material={materials['METALIC.002']} position={[-0.18, 1.264, -2.116]} rotation={[Math.PI, -0.186, Math.PI]} scale={0.115} />
      <mesh geometry={nodes.Circle037.geometry} material={materials.METALIC} position={[-0.052, 1.124, -2.137]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle036.geometry} material={materials['Material.031']} position={[-0.272, 1.124, -1.92]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle035.geometry} material={materials.METALIC} position={[-0.301, 1.124, -2.275]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle034.geometry} material={materials.METALIC} position={[-0.445, 1.124, -2.016]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle033.geometry} material={materials.METALIC} position={[-0.024, 1.124, -1.782]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle032.geometry} material={materials.METALIC} position={[0.12, 1.124, -2.041]} rotation={[-Math.PI, -1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle031.geometry} material={materials.METALIC} position={[0.377, 1.122, -1.697]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
      <mesh geometry={nodes.Circle030.geometry} material={materials.METALIC} position={[0.429, 1.122, -1.791]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
      <mesh geometry={nodes.Circle029.geometry} material={materials.METALIC} position={[0.547, 1.122, -1.726]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
      <mesh geometry={nodes.Circle028.geometry} material={materials.METALIC} position={[0.494, 1.122, -1.631]} rotation={[Math.PI, -1.064, 0]} scale={0.128} />
      <mesh geometry={nodes.Circle027.geometry} material={materials.METALIC} position={[2.153, 1.178, -0.96]} rotation={[-1.035, 0.31, -0.974]} scale={0.078} />
      <mesh geometry={nodes.Circle026.geometry} material={materials.METALIC} position={[2.214, 1.178, -0.896]} rotation={[-0.937, 0.47, -0.984]} scale={0.078} />
      <mesh geometry={nodes.Circle025.geometry} material={materials.METALIC} position={[2.273, 1.178, -0.831]} rotation={[0.948, 0.477, -2.062]} scale={0.078} />
      <mesh geometry={nodes.Circle024.geometry} material={materials.METALIC} position={[2.331, 1.178, -0.767]} rotation={[0.604, 0.654, -1.916]} scale={0.078} />
      <mesh geometry={nodes.Circle023.geometry} material={materials.METALIC} position={[2.394, 1.178, -0.703]} rotation={[-0.17, 0.734, -1.442]} scale={0.078} />
      <mesh geometry={nodes.Circle022.geometry} material={materials.METALIC} position={[2.441, 1.177, -0.628]} rotation={[0.895, 0.472, -2.113]} scale={0.078} />
      <mesh geometry={nodes.Circle021.geometry} material={materials.METALIC} position={[-0.803, 1.194, -1.892]} rotation={[-1.72, -0.017, 1.689]} scale={0.017} />
      <mesh geometry={nodes.Circle020.geometry} material={materials.METALIC} position={[-0.805, 1.194, -1.892]} rotation={[Math.PI / 2, 0, -1.671]} scale={0.018} />
      <mesh geometry={nodes.Circle019.geometry} material={materials.METALIC} position={[-0.578, 1.261, -1.683]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle018.geometry} material={materials.METALIC} position={[-0.352, 1.261, -1.625]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle017.geometry} material={materials.METALIC} position={[-0.309, 1.261, -1.675]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle016.geometry} material={materials.METALIC} position={[-0.162, 1.261, -1.672]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle015.geometry} material={materials.METALIC} position={[-0.088, 1.26, -1.596]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle014.geometry} material={materials.METALIC} position={[0.088, 1.26, -1.445]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle013.geometry} material={materials.METALIC} position={[0.023, 1.261, -1.776]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle012.geometry} material={materials.METALIC} position={[-0.162, 1.261, -1.878]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle011.geometry} material={materials.METALIC} position={[-0.022, 1.261, -2.132]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle010.geometry} material={materials.METALIC} position={[-0.294, 1.26, -1.914]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle009.geometry} material={materials.METALIC} position={[-0.117, 1.261, -2.212]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle008.geometry} material={materials['METALIC.001']} position={[-0.161, 1.264, -2.149]} rotation={[0, 1.064, 0]} scale={0.115} />
      <mesh geometry={nodes.Circle007.geometry} material={materials.METALIC} position={[0.153, 1.261, -2.089]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle006.geometry} material={materials.METALIC} position={[0.162, 1.261, -2.026]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle005.geometry} material={materials.METALIC} position={[0.203, 1.261, -2.033]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle004.geometry} material={materials.METALIC} position={[0.517, 1.261, -1.861]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle003.geometry} material={materials.METALIC} position={[0.334, 1.261, -1.931]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle002.geometry} material={materials.METALIC} position={[0.197, 1.261, -1.682]} rotation={[0, 1.064, 0]} scale={0.106} />
      <mesh geometry={nodes.Circle.geometry} material={materials.METALIC} position={[0.243, 1.261, -1.308]} rotation={[0, 1.064, 0]} scale={0.106} />
    </group>
  )
}

useGLTF.preload('/models/room/untitled.gltf')
